<h1>CSV-Files</h1>
CSV stands for "Comma Separated Values" and means that we store data in a list. List elements are separated using commas. Sometimes, other symbold are used as delimiters, such as semicolons, tabspaces, return, etc. Often, commas separate columns and return separates lines, creating a table rather than a list. Such a list or table is saved as a CSV file. CSV files usually contain strings that are saved using UTF-8, ANSI, or other character sets. CSV files have several strengths:
<ul>
    <li>In contrast to binary files, the raw text of CSV files (as displayed by text editors) is interpretable by readers (if not compressed)</li>
    <li>CSV files can be imported and exported by spreadsheet softwares, like Google Docs, Microsoft Excel, <a href="https://www.openoffice.org/" target="_blank">Open Office Calc</a> and <a href="https://de.libreoffice.org/" target="_blank">Libre Office Calc</a>, by statistical softwares, such as IBM SPSS and <a href="https://cran.r-project.org/bin/windows/base/" target="_blank">R</a>, by database softwares, like <a href="https://www.mysql.com/" target="_blank">MySQL</a>, and by audio softwares, like <a href="https://www.audacity.de/" target="_blank">Audacity</a> and <a href="https://sonification.highcharts.com/#/app" target="_blank">Highchart Sonification Studio</a></li>
</ul>
Some weaknesses of CSF files are:
<ul>
    <li>CSV files tend to be larger than binary files</li>
    <li>CSV files are only semi-<a href="https://datatracker.ietf.org/doc/html/rfc4180.html" target="_blank">standardized</a> for lists and tables, but not for higher order arrays and matrices</li>
    <li>The option to use any symbol as separator and arbitrary symbols (usually single quote or double quote) to indicate a string can cause confusion and unexpected text display</li>
    <li>Language settings can cause awkward tables, as Germans use commas as decimal separator and, sometimes, points as thousands separator. In English it is the other way round. Language settings can even descroy existing CSV files by overwriting commas with points or the other way round.</li>
    <li>Small errors that a human makes when manually editing a csv file can cause unexpected harm</li>
</ul>

<h2>Pandas</h2>
Pandas is often used to import, handle, analyze and export data.

In [2]:
#pip install pandas
import pandas as pd

You can easily import a CSV file

In [4]:
a_list = pd.read_table('composers.csv', sep=',')

and display its content

In [5]:
a_list

                      name  birth  death
0    Johann Sebastian Bach   1685   1750
1                John Blow   1649   1708
2              John Eccles   1668   1735
3   Georg Friedrich Händel   1685   1759
4             Marin Marais   1656   1728
5       Claudio Monteverdi   1567   1643
6         Johann Pachelbel   1653   1706
7           Daniel Purcell   1664   1717
8            Henry Purcell   1659   1695
9   Georg Philipp Telemann   1681   1767
10      Pietro Della Valle   1586   1652
11         Antonio Vivaldi   1678   1741

If the CSV files uses other delimiters, you can indicate them as sep <font color=#a2f>= </font><font color=#ba2121>'delimiter'</font>

In [7]:
b_list = pd.read_table('composers-semicolon.csv',sep=';')
b_list

                      name  birth  death
0    Johann Sebastian Bach   1685   1750
1                John Blow   1649   1708
2              John Eccles   1668   1735
3   Georg Friedrich Händel   1685   1759
4             Marin Marais   1656   1728
5       Claudio Monteverdi   1567   1643
6         Johann Pachelbel   1653   1706
7           Daniel Purcell   1664   1717
8            Henry Purcell   1659   1695
9   Georg Philipp Telemann   1681   1767
10      Pietro Della Valle   1586   1652
11         Antonio Vivaldi   1678   1741